"""
Django settings for HBS_Project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f247#btkri*v8$@^pbnr7mf@&#llh59-*$x7b5p^-$d4&gwsjp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['django-djreact-app-d5af3d4e3559.herokuapp.com']
ALLOWED_HOSTS = ['www.recychbsadmin.in']
ALLOWED_HOSTS = ['www.app.recychbs.in']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # WhiteNoise for static files during development
    'django.contrib.staticfiles',
    'CustomUser',
    'corsheaders',
    'storages',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Should come before AuthenticationMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Correctly placed
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'HBS_Project.urls'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'assets/'

STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dist','assets'),
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HBS_Project.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'recychbs_db',
        'HOST':'82.112.238.156',
        'USER':'vpsdb',
        'PASSWORD':'Hudsmer@123',
        'PORT':'3306',
        
    }
}

# AUTH_USER_MODEL = 'CustomUser.User'


# MEDIA_ROOT = '/media/'

# MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # React app's URL
    'http://localhost:5174',
    'https://www.app.recychbs.in',
    'https://www.recychbsadmin.in',  # React app's URL
    'https://adminapp-46edb27550db.herokuapp.com',  # React app's URL
    'https://hsb-admin-ui.onrender.com',
    'https://hsb-ui.onrender.com',
    'https://hbs-admin-afcea2f2324b.herokuapp.com',
    'https://new-hbs-admin-82beda5bc10a.herokuapp.com',
    'chrome-extension://eejfoncpjfgmeleakejdcanedmefagga',

    # 'https://demo-djreact-recyc-app-ee540343796a.herokuapp.com'

]

CORS_ORGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True  # Allow credentials like cookies to be included

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',  # React app's URL
    'http://localhost:5174',
    'https://www.app.recychbs.in',
    'https://www.recychbsadmin.in/',  # React app's URL
    'https://adminapp-46edb27550db.herokuapp.com',  # React app's URL
    'https://hsb-admin-ui.onrender.com',
    'https://hsb-ui.onrender.com',
    'https://hbs-admin-afcea2f2324b.herokuapp.com',
    'https://new-hbs-admin-82beda5bc10a.herokuapp.com',
    # 'https://demo-djreact-recyc-app-ee540343796a.herokuapp.com'

]


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Default: use database for session storage

# Important for allowing cross-origin cookies to be shared:
SESSION_COOKIE_SAMESITE = None  # Allow the session cookie to be shared across different origins
SESSION_COOKIE_SECURE = False  # Set to True in production when using HTTPS
CORS_ALLOW_CREDENTIALS = True# settings.py
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
# Set session to expire after a certain number of seconds
SESSION_COOKIE_AGE = 1209600  # 2 weeks, default is 1209600 seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session active even after browser close
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


django_heroku.settings(locals())






from django.conf import settings


# SEND EMAIL

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'recychbs.in@gmail.com'
EMAIL_HOST_PASSWORD = 'lbvvmotxwzvyyawm'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


PASSWORD_RESET_TIMEOUT_DAYS = 1  # Password reset token will be valid for 1 day


# For development (to see the email in the terminal)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# CSRF_TRUSTED_ORIGINS = [
#     'chrome-extension://eejfoncpjfgmeleakejdcanedmefagga',
# ]


# settings.py (Django)
FRONTEND_URL = "https://www.app.recychbs.in/"  # Set this to your actual frontend URL

GDAL_LIBRARY_PATH = os.path.join('C:\\OSGeo4W\\bin\\adal.dll')  # Adjust 'gdal304.dll' as necessary
